[stage]
pubsub = [
  "redisstg1",
  "redisstg2",
  "redisstg3"
]
keepalive = true
heartbeat = "500ms"

[development]
pubsub = [
  "localhost:7788"
]
keepalive = false
heartbeat = "1s"

[production]
pubsub = [
  "redisprod1",
  "redisprod2"
]
keepalive = true
heartbeat = "200ms"
